python dataset_evaluator.py ~/hd/LS3DC ls3dc -s -p -b --dataset_folder_name dataset_pccs_merged_$1_after_noise --data_folder_name hpnet_pred_max --result_folder_name eval_hpnet_pred_fit --gt_data_folder_name data --gt_format ls3dc  --ignore_primitives_orientation -crf 1 --no_use_data_primitives
python dataset_evaluator.py ~/hd/LS3DC ls3dc -s -p -b --dataset_folder_name dataset_pccs_merged_$1_after_noise --data_folder_name hpnet_pred_max --result_folder_name eval_hpnet_pred_max --gt_data_folder_name data --gt_format ls3dc  --ignore_primitives_orientation -crf 1
python dataset_evaluator.py ~/hd/LS3DC ls3dc -s -p -b --dataset_folder_name dataset_pccs_merged_$1_after_noise --data_folder_name hpnet_pred_wm --result_folder_name eval_hpnet_pred_wm --gt_data_folder_name data --gt_format ls3dc  --ignore_primitives_orientation -crf 1

python dataset_evaluator.py ~/hd/LS3DC ls3dc -s -p -b --dataset_folder_name dataset_pccs_merged_$1_after_noise --data_folder_name parsenet_pred_max --result_folder_name eval_parsenet_pred_fit --gt_data_folder_name data --gt_format ls3dc  --ignore_primitives_orientation -crf 1 --no_use_data_primitives
python dataset_evaluator.py ~/hd/LS3DC ls3dc -s -p -b --dataset_folder_name dataset_pccs_merged_$1_after_noise --data_folder_name parsenet_pred_max --result_folder_name eval_parsenet_pred_max --gt_data_folder_name data --gt_format ls3dc  --ignore_primitives_orientation -crf 1
python dataset_evaluator.py ~/hd/LS3DC ls3dc -s -p -b --dataset_folder_name dataset_pccs_merged_$1_after_noise --data_folder_name parsenet_pred_wm --result_folder_name eval_parsenet_pred_wm --gt_data_folder_name data --gt_format ls3dc  --ignore_primitives_orientation -crf 1

python dataset_evaluator.py ~/hd/LS3DC ls3dc -s -p -b --dataset_folder_name dataset_pccs_merged_$1_after_noise --data_folder_name eff_ransac_result_max/output_h5 --result_folder_name eval_eff_ransac_result_fit --gt_data_folder_name data --gt_format ls3dc --ignore_primitives_orientation -crf 1 --no_use_data_primitives
python dataset_evaluator.py ~/hd/LS3DC ls3dc -s -p -b --dataset_folder_name dataset_pccs_merged_$1_after_noise --data_folder_name eff_ransac_result_max/output_h5 --result_folder_name eval_eff_ransac_result_max --gt_data_folder_name data --gt_format ls3dc  --ignore_primitives_orientation -crf 1
python dataset_evaluator.py ~/hd/LS3DC ls3dc -s -p -b --dataset_folder_name dataset_pccs_merged_$1_after_noise --data_folder_name eff_ransac_result_wm/output_h5 --result_folder_name eval_eff_ransac_result_wm --gt_data_folder_name data --gt_format ls3dc  --ignore_primitives_orientation -crf 1