python dataset_merger.py ~/hd/LS3DC ls3dc ls3dc --input_dataset_folder_name dataset_pccs_divided_$1_after_noise --output_dataset_folder_name dataset_pccs_merged_$1_after_noise --input_data_folder_name data --output_data_folder_name data

python dataset_merger.py ~/hd/LS3DC hpnet ls3dc --input_dataset_folder_name dataset_pccs_divided_$1_after_noise --output_dataset_folder_name dataset_pccs_merged_$1_after_noise --input_data_folder_name hpnet_pred --output_data_folder_name hpnet_pred_max --input_gt_data_folder_name data --merge_method max --no_use_data_primitives
python dataset_merger.py ~/hd/LS3DC hpnet ls3dc --input_dataset_folder_name dataset_pccs_divided_$1_after_noise --output_dataset_folder_name dataset_pccs_merged_$1_after_noise --input_data_folder_name hpnet_pred --output_data_folder_name hpnet_pred_wm --input_gt_data_folder_name data --merge_method wm --no_use_data_primitives

python dataset_merger.py ~/hd/LS3DC parsenet ls3dc --input_dataset_folder_name dataset_pccs_divided_$1_after_noise --output_dataset_folder_name dataset_pccs_merged_$1_after_noise --input_data_folder_name parsenet_pred --output_data_folder_name parsenet_pred_max --input_gt_data_folder_name data --merge_method max --no_use_data_primitives
python dataset_merger.py ~/hd/LS3DC parsenet ls3dc --input_dataset_folder_name dataset_pccs_divided_$1_after_noise --output_dataset_folder_name dataset_pccs_merged_$1_after_noise --input_data_folder_name parsenet_pred --output_data_folder_name parsenet_pred_wm --input_gt_data_folder_name data --merge_method wm --no_use_data_primitives

python dataset_merger.py ~/hd/LS3DC ls3dc ls3dc --input_dataset_folder_name dataset_pccs_divided_$1_after_noise --output_dataset_folder_name dataset_pccs_merged_$1_after_noise --input_data_folder_name eff_ransac_result/output_h5 --output_data_folder_name eff_ransac_result_max/output_h5 --input_gt_data_folder_name data --merge_method max
python dataset_merger.py ~/hd/LS3DC ls3dc ls3dc --input_dataset_folder_name dataset_pccs_divided_$1_after_noise --output_dataset_folder_name dataset_pccs_merged_$1_after_noise --input_data_folder_name eff_ransac_result/output_h5 --output_data_folder_name eff_ransac_result_wm/output_h5 --input_gt_data_folder_name data --merge_method wm